### ISSUE TITLE
Wrong Player Count

### ISSUE THREAD

**Issue by jaythomas77** [yapb/yapb#187]
In server browser total player count is = bot in spec + actual Players.
Other bots who have joined team aren't showing in Server Browser.
yb_enable_query_hook "1"

Steam-Browser
![steambrowser](https://user-images.githubusercontent.com/58573008/97140194-175b9f80-1782-11eb-9eca-8b29d3ad1808.jpg)

Ingame Browser
![ingame](https://user-images.githubusercontent.com/58573008/97140206-1b87bd00-1782-11eb-8182-5e889025b4c6.jpg)

**Comment by jeefo** [comment]
yb_enable_query_hook is not enabled / not working.

Since this:
![3mhwlrn 1](https://user-images.githubusercontent.com/1781346/99104599-3f585900-25f2-11eb-8f6f-a492f3c56458.png)

and this:
![FQpKPh9 1](https://user-images.githubusercontent.com/1781346/99104644-5008cf00-25f2-11eb-8c4a-7e4c63ac119d.png)


Players counts are totally not controlled by bots. Steam deciding himself.
