### ISSUE TITLE
Add support for 3rd party menu

### ISSUE THREAD

**Issue by EVOLCORE** [yapb/yapb#197]
Hello, please add 3rd party menu support for bots selection csdm weapons, because i have selected csdm mode and they not choosing weapons still play with knifes, also jason mode disabled

**Comment by jeefo** [comment]
Hi. I didn't quite understand what did you want. What mod do you use, other plugins, what is expected behaviour, what is not.

As for mods, Vanilla CSDM working fine with bots. I don't know what mod do you use. But before you're ask, i will not add dedicated support for any third party mods other than Alliedmods CSDM. Bot (not only yapb) support should be added by their authors.

**Comment by EVOLCORE** [comment]
I am not using any mod, it's simple settings for deatmatch in regamedll and 3rd party weapon menu plugin that's all and bots are not selecting weapons from that menu

**Comment by jeefo** [comment]
you should add support for boys for that third-party  weapon menu plugin
