### ISSUE TITLE
Fake ping feature is broken

### ISSUE THREAD

**Issue by regener** [yapb/yapb#227]
**Describe the bug**
I have set the following cvars in yapb.cfg:
yb_show_latency "2"
yb_ping_base_min "1"
yb_ping_base_min "3"

But instead of 1-3 bots still have 40-50 ping in the scoreboard and players ping is lower than the real value.
For example in console using the "ping" command I have a ping of 24, but the scoreboard shows 15.
If I turn off the fake ping feature (yb_show_latency 0) then it shows the same at both places (24).

In the other hand setting yb_show_latency to 1 does not display the BOT text in the scoreboard.

**Environment details:**
 - OS: debian 9 and 10 (tested on 2 servers)
 - Engine: rehlds 3.8.0.702
 - GameDLL: regamedll 5.20.0.492
 - Metamod: Metamod-r v1.3.0.128
 - Bot Version: v4.2.597
 - Game mode: public

This is like the opposite of: https://github.com/yapb/yapb/issues/160

**Comment by jeefo** [comment]
As for player ping it's should be fixed in https://github.com/yapb/yapb/commit/e213e39d172d79a45fa6b557fdb538777fecdfe5

As for bots, it's ping _base_ not the bounds from which ping is selected. To base ping there's another computation done, to take in account average ping for humans.

Probably if difference between base_min and base_max is less then 5, we can't take random value between them directly without taking in account average ping on server.

**Comment by jeefo** [comment]
> I can also confirm. Also noticed the latency data on bots periodically goes blank in scoreboard then returns to working order second after.

this is a result of bad fps on server, will fix this later.

**Comment by iclassdon** [comment]
Excellent update confirmed working now.
