### ISSUE TITLE
disable bot jump and duck

### ISSUE THREAD

**Issue by kakadoo123** [yapb/yapb#358]
a bot is easily detected as bot because he jumps and ducks like a dumbie... so make a config to disable all duck, jump. i already saw there is disabling walk possible

**Comment by Vladislav4KZ** [comment]
And how do you imagine how bots with jumps and crouches disabled will play when they need to jump over an obstacle, or crawl through it?

Disabling jumps and crouches is not a good solution to make bots look more like human players.

This mechanism is made to overcome obstacles, so that the bots do not stand in one place.
