### ISSUE TITLE
Can't build yapb.so.p/src_message.cpp in Alpine Linux

### ISSUE THREAD

**Issue by DvaMishkiLapa** [yapb/yapb#561]
Good afternoon. Thank you very much for implementing this project. I am trying to build a library according to [this tutorial](https://yapb.readthedocs.io/ru/latest/building.html#linux) for postmarketOS (Alpine Linux), but I get a compilation error. What could be the problem?

Config:
OS: `Linux google-kukui 6.6.25-mt8183 #1-postmarketos-mediatek-mt8183 SMP PREEMPT Fri Apr 12 13:06:02  aarch64 Linux`
Ninja version: 1.9
Meson version: 1.4.0
g++:
```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-alpine-linux-musl/13.2.1/lto-wrapper
Target: aarch64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-13-20240309/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=aarch64-alpine-linux-musl --host=aarch64-alpine-linux-musl --target=aarch64-alpine-linux-musl --enable-checking=release --disable-cet --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,d,objc,go,fortran,ada --enable-link-serialization=2 --enable-linker-build-id --with-arch=armv8-a --with-abi=lp64 --disable-libquadmath --disable-libssp --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 13.2.1_git20240309'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.2.1 20240309 (Alpine 13.2.1_git20240309) 
```
gcc:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-alpine-linux-musl/13.2.1/lto-wrapper
Target: aarch64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-13-20240309/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=aarch64-alpine-linux-musl --host=aarch64-alpine-linux-musl --target=aarch64-alpine-linux-musl --enable-checking=release --disable-cet --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,d,objc,go,fortran,ada --enable-link-serialization=2 --enable-linker-build-id --with-arch=armv8-a --with-abi=lp64 --disable-libquadmath --disable-libssp --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 13.2.1_git20240309'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.2.1 20240309 (Alpine 13.2.1_git20240309) 
```
clang:
```
Alpine clang version 17.0.6
Target: aarch64-alpine-linux-musl
Thread model: posix
InstalledDir: /usr/bin
Configuration file: /etc/clang17/aarch64-alpine-linux-musl.cfg
```

Build log file: [build.log](https://github.com/yapb/yapb/files/15142615/build.log)

I'd also like to clarify. I'm trying to build bots for [xash3d](https://github.com/FWGS/xash3d-fwgs), which I built for x64. I also built [hlsdk](https://github.com/FWGS/hlsdk-portable) for x64. Does your library work for x64, or is it easier for me to build everything for x32?

**Comment by jeefo** [comment]
Hello, try to build from continious branch.Sent from my Galaxy-------- Original message --------From: Artem ***@***.***> Date: 4/28/24  18:27  (GMT+03:00) To: yapb/yapb ***@***.***> Cc: Subscribed ***@***.***> Subject: [yapb/yapb] Can't build yapb.so.p/src_message.cpp in Alpine Linux (Issue #561) 
Good afternoon. Thank you very much for implementing this project. I am trying to build a library according to this tutorial for postmarketOS (Alpine Linux), but I get a compilation error. What could be the problem?
Config:
OS: Linux google-kukui 6.6.25-mt8183 #1-postmarketos-mediatek-mt8183 SMP PREEMPT Fri Apr 12 13:06:02  aarch64 Linux
Ninja version: 1.9
Meson version: 1.4.0
g++:
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-alpine-linux-musl/13.2.1/lto-wrapper
Target: aarch64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-13-20240309/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=aarch64-alpine-linux-musl --host=aarch64-alpine-linux-musl --target=aarch64-alpine-linux-musl --enable-checking=release --disable-cet --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,d,objc,go,fortran,ada --enable-link-serialization=2 --enable-linker-build-id --with-arch=armv8-a --with-abi=lp64 --disable-libquadmath --disable-libssp --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 13.2.1_git20240309'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.2.1 20240309 (Alpine 13.2.1_git20240309) 

gcc:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-alpine-linux-musl/13.2.1/lto-wrapper
Target: aarch64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-13-20240309/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=aarch64-alpine-linux-musl --host=aarch64-alpine-linux-musl --target=aarch64-alpine-linux-musl --enable-checking=release --disable-cet --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,d,objc,go,fortran,ada --enable-link-serialization=2 --enable-linker-build-id --with-arch=armv8-a --with-abi=lp64 --disable-libquadmath --disable-libssp --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 13.2.1_git20240309'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 13.2.1 20240309 (Alpine 13.2.1_git20240309) 

clang:
Alpine clang version 17.0.6
Target: aarch64-alpine-linux-musl
Thread model: posix
InstalledDir: /usr/bin
Configuration file: /etc/clang17/aarch64-alpine-linux-musl.cfg

Build log file: build.log
I'd also like to clarify. I'm trying to build bots for xash3d, which I built for x64. I also built hlsdk for x64. Does your library work for x64, or is it easier for me to build everything for x32?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yapb/yapb/issues/561",
"url": "https://github.com/yapb/yapb/issues/561",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DvaMishkiLapa** [comment]
> Hello, try to build from continious branch.

I tried building from master and chatter-fixes-and-improvements, the errors seem to be the same.

**Comment by jeefo** [comment]
could you try ?

**Comment by jeefo** [comment]
You're need master branch with recursively updated submodules.

**Comment by DvaMishkiLapa** [comment]
Yes, I forgot to change the branch, of course.

New error in link stage:
[build-ld.log](https://github.com/yapb/yapb/files/15192337/build-ld.log)

**Comment by jeefo** [comment]
Change ``'werror=true',`` to ``'werror=false',`` in the meson.build, this is a fake-positive warning, however i will try to fix in future, just don't have fresh gcc on my aaarch64 machine.

**Comment by DvaMishkiLapa** [comment]
It seems to be working. But I can't connect to any server. And also creating my own server is not active in the main menu.

Xash3d 49/0.20

liblist.gam
```
game "Counter-Strike"
url_info "www.counter-strike.net"
url_dl ""
version "1.6"
size "184000000"
svonly "0"
cldll "1"
hlversion "1120"
nomodels "1"
nohimodel "1"
mpentity "info_player_start"
secure "1"
type "multiplayer_only"
gamedll "addons/yapb/bin/yapb.so"
trainmap "tr_1"
```

gameinfo.txt 
```
// generated by Xash3D FWGS 0.20-f4a77308 (linux-arm64)

basedir		"valve"
gamedir		"cstrike"
title		"Counter-Strike"
startmap		"newmap"
trainmap		"tr_1"
version		1.6
size		184000000
url_info		"www.counter-strike.net"
type		"Multiplayer"
dllpath		"cl_dlls"
gamedll		"addons/yapb/bin/yapb.so"
gamedll_linux		"addons/yapb/bin/yapb.so"
gamedll_osx		"addons/yapb/bin/yapb.dylib"
icon		"game.ico"
gamemode		"multiplayer_only"
sp_entity		"info_player_start"
mp_entity		"info_player_start"
secure		"1"
nomodels		"1"
max_edicts	1200
max_tempents	500
max_beams		128
max_particles	4096
quicksave_aged_count		0
autosave_aged_count		0
internal_vgui_support		0
render_picbutton_text		0
```

Or should I go to the Xash3d community?

**Comment by jeefo** [comment]
Mine is loading on xashds, not sure about listenservers...

**Comment by jeefo** [comment]
Does it work without bots?

**Comment by DvaMishkiLapa** [comment]
The game launches with the configuration above, but I literally can't even launch any map. The LAN or server startup items are not active.

I'm pretty sure I'm misconfiguring something though. I checked the HL launch to make sure I built Xash3d and the SDK correctly - single-player is working.

**Comment by jeefo** [comment]
closed as inactive
